import Layout from '/components/Layout'

export default function SpecialCases() {
    return (
        <>
            <Layout title='Casos Especiales' descripcion='Casos Especiales' navTitle='Casos Especiales' ruta='specials'>
                <h1>Casos Especiales.</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
                <br/>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
                <br/>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
                <br/>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
                <br/>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
                <br/>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, aliquid amet aperiam at culpa cumque delectus explicabo fuga laborum magnam, nam, neque optio pariatur quibusdam quidem quisquam quod repellat vel!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet assumenda consequuntur deserunt impedit iure natus provident quas repellat repellendus sequi, veniam voluptatibus. Dolorem illo neque quidem rerum similique!</p>
            </Layout>
        </>
    )
}
